// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: find_email.sql

package database

import (
	"context"
)

const findEmail = `-- name: FindEmail :one
SELECT id, created_at, updated_at, email, hashed_password FROM users 
WHERE email = $1
`

func (q *Queries) FindEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
