// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: revoke_toke.sql

package database

import (
	"context"
)

const revokeToken = `-- name: RevokeToken :exec

UPDATE refresh_tokens
SET updated_at = NOW(),
    revoked_at = NOW(),
    token = 'revoked'
WHERE token = $1
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}
